/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
 *
 * This file is auto-generated by cli/generate-config.ts
 * Run 'npm run generate:config' to regenerate
 */

// =============================================================================
// Types
// =============================================================================

export interface ExampleConfig {
  /** Path to the Solidity contract file */
  contract: string;
  /** Path to the TypeScript test file */
  test: string;
  /** Optional additional contract dependencies */
  dependencies?: string[];
  /** Optional npm packages to install */
  npmDependencies?: Record<string, string>;
  /** Full description for documentation */
  description: string;
  /** Category for grouping */
  category: string;
  /** Output path for generated documentation */
  docsOutput: string;
  /** Title for documentation */
  title: string;
}

export interface CategoryConfig {
  /** Display name */
  name: string;
  /** List of contracts in this category */
  contracts: Array<{ sol: string; test?: string }>;
}

// =============================================================================
// Example Configurations
// =============================================================================

export const EXAMPLES: Record<string, ExampleConfig> = {
  "blind-auction": {
    contract: "contracts/advanced/BlindAuction.sol",
    test: "test/advanced/BlindAuction.ts",
    description:
      "Blind Auction with encrypted bids - only the winning price is revealed",
    category: "Advanced",
    docsOutput: "docs/advanced/blind-auction.md",
    title: "Blind Auction",
  },
  "encrypted-escrow": {
    contract: "contracts/advanced/EncryptedEscrow.sol",
    test: "test/advanced/EncryptedEscrow.ts",
    description: "Encrypted Escrow service - amounts hidden until release!",
    category: "Advanced",
    docsOutput: "docs/advanced/encrypted-escrow.md",
    title: "Encrypted Escrow",
  },
  "hidden-voting": {
    contract: "contracts/advanced/HiddenVoting.sol",
    test: "test/advanced/HiddenVoting.ts",
    description:
      "Hidden Voting with encrypted ballots and homomorphic tallying",
    category: "Advanced",
    docsOutput: "docs/advanced/hidden-voting.md",
    title: "Hidden Voting",
  },
  "private-kyc": {
    contract: "contracts/advanced/PrivateKYC.sol",
    test: "test/advanced/PrivateKYC.ts",
    description:
      "Private KYC - verify identity without revealing personal data!",
    category: "Advanced",
    docsOutput: "docs/advanced/private-kyc.md",
    title: "Private KYC",
  },
  "private-payroll": {
    contract: "contracts/advanced/PrivatePayroll.sol",
    test: "test/advanced/PrivatePayroll.ts",
    description:
      "Private Payroll system - salaries stay encrypted, only employees see their own!",
    category: "Advanced",
    docsOutput: "docs/advanced/private-payroll.md",
    title: "Private Payroll",
  },
  "public-decrypt-multiple-values": {
    contract: "contracts/basic/decryption/PublicDecryptMultipleValues.sol",
    test: "test/basic/decryption/PublicDecryptMultipleValues.ts",
    description:
      "Implements a simple 8-sided Die Roll game demonstrating public, permissionless decryption",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/public-decrypt-multiple-values.md",
    title: "Public Decrypt Multiple Values",
  },
  "public-decrypt-single-value": {
    contract: "contracts/basic/decryption/PublicDecryptSingleValue.sol",
    test: "test/basic/decryption/PublicDecryptSingleValue.ts",
    description:
      "Implements a simple Heads or Tails game demonstrating public, permissionless decryption",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/public-decrypt-single-value.md",
    title: "Public Decrypt Single Value",
  },
  "user-decrypt-multiple-values": {
    contract: "contracts/basic/decryption/UserDecryptMultipleValues.sol",
    test: "test/basic/decryption/UserDecryptMultipleValues.ts",
    description: "Demonstrates user decryption of multiple encrypted values",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/user-decrypt-multiple-values.md",
    title: "User Decrypt Multiple Values",
  },
  "user-decrypt-single-value": {
    contract: "contracts/basic/decryption/UserDecryptSingleValue.sol",
    test: "test/basic/decryption/UserDecryptSingleValue.ts",
    description:
      "Demonstrates the FHE decryption mechanism and highlights common pitfalls",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/user-decrypt-single-value.md",
    title: "User Decrypt Single Value",
  },
  "encrypt-multiple-values": {
    contract: "contracts/basic/encryption/EncryptMultipleValues.sol",
    test: "test/basic/encryption/EncryptMultipleValues.ts",
    description:
      "Encrypting and handling multiple values in a single transaction efficiently.",
    category: "Basic - Encryption",
    docsOutput: "docs/basic/encryption/encrypt-multiple-values.md",
    title: "Encrypt Multiple Values",
  },
  "encrypt-single-value": {
    contract: "contracts/basic/encryption/EncryptSingleValue.sol",
    test: "test/basic/encryption/EncryptSingleValue.ts",
    description:
      "FHE encryption mechanism with single values, including common pitfalls and best practices for developers.",
    category: "Basic - Encryption",
    docsOutput: "docs/basic/encryption/encrypt-single-value.md",
    title: "Encrypt Single Value",
  },
  "fhe-counter": {
    contract: "contracts/basic/encryption/FHECounter.sol",
    test: "test/basic/encryption/FHECounter.ts",
    description:
      "Confidential counter implementation using FHEVM, compared with a standard counter to highlight encryption benefits.",
    category: "Basic - Encryption",
    docsOutput: "docs/basic/encryption/fhe-counter.md",
    title: "FHE Counter",
  },
  "fhe-add": {
    contract: "contracts/basic/fhe-operations/FHEAdd.sol",
    test: "test/basic/fhe-operations/FHEAdd.ts",
    description: "Simple example: adding two encrypted values (a + b)",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-add.md",
    title: "FHE Add",
  },
  "fhe-arithmetic": {
    contract: "contracts/basic/fhe-operations/FHEArithmetic.sol",
    test: "test/basic/fhe-operations/FHEArithmetic.ts",
    description:
      "Demonstrates all FHE arithmetic operations on encrypted integers",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-arithmetic.md",
    title: "FHE Arithmetic",
  },
  "fhe-comparison": {
    contract: "contracts/basic/fhe-operations/FHEComparison.sol",
    test: "test/basic/fhe-operations/FHEComparison.ts",
    description:
      "Demonstrates all FHE comparison operations on encrypted integers",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-comparison.md",
    title: "FHE Comparison",
  },
  "fhe-if-then-else": {
    contract: "contracts/basic/fhe-operations/FHEIfThenElse.sol",
    test: "test/basic/fhe-operations/FHEIfThenElse.ts",
    description:
      "Demonstrates conditional logic: max(a, b) using encrypted comparison",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-if-then-else.md",
    title: "FHE If Then Else",
  },
  "fhe-access-control": {
    contract: "contracts/concepts/FHEAccessControl.sol",
    test: "test/concepts/FHEAccessControl.ts",
    description:
      "Critical access control patterns in FHEVM: FHE.allow, FHE.allowThis, FHE.allowTransient. Includes common mistakes and correct implementations.",
    category: "Concepts",
    docsOutput: "docs/concepts/fhe-access-control.md",
    title: "FHE Access Control",
  },
  "fhe-anti-patterns": {
    contract: "contracts/concepts/FHEAntiPatterns.sol",
    test: "test/concepts/FHEAntiPatterns.ts",
    description:
      "Common FHE mistakes and their correct alternatives. Covers: branching, permissions, require/revert, re-encryption, loops, noise, and deprecated APIs.",
    category: "Concepts",
    docsOutput: "docs/concepts/fhe-anti-patterns.md",
    title: "FHE Anti Patterns",
  },
  "fhe-handles": {
    contract: "contracts/concepts/FHEHandles.sol",
    test: "test/concepts/FHEHandles.ts",
    description:
      "Understanding FHE handles: creation, computation, immutability, and symbolic execution in mock mode.",
    category: "Concepts",
    docsOutput: "docs/concepts/fhe-handles.md",
    title: "FHE Handles",
  },
  "fhe-input-proof": {
    contract: "contracts/concepts/FHEInputProof.sol",
    test: "test/concepts/FHEInputProof.ts",
    description:
      "Explains input proof validation in FHEVM: what proofs are, why they are needed, and how to use them correctly with single and batched inputs.",
    category: "Concepts",
    docsOutput: "docs/concepts/fhe-input-proof.md",
    title: "FHE Input Proof",
  },
  "encrypted-lottery": {
    contract: "contracts/gaming/EncryptedLottery.sol",
    test: "test/gaming/EncryptedLottery.ts",
    description:
      "Encrypted Lottery with private ticket numbers - fair and verifiable!",
    category: "Gaming",
    docsOutput: "docs/gaming/encrypted-lottery.md",
    title: "Encrypted Lottery",
  },
  "encrypted-poker": {
    contract: "contracts/gaming/EncryptedPoker.sol",
    test: "test/gaming/EncryptedPoker.ts",
    description: "Encrypted Poker - Texas Hold'em with hidden hole cards!",
    category: "Gaming",
    docsOutput: "docs/gaming/encrypted-poker.md",
    title: "Encrypted Poker",
  },
  "rock-paper-scissors": {
    contract: "contracts/gaming/RockPaperScissors.sol",
    test: "test/gaming/RockPaperScissors.ts",
    description:
      "Rock-Paper-Scissors game with encrypted moves - fair play guaranteed!",
    category: "Gaming",
    docsOutput: "docs/gaming/rock-paper-scissors.md",
    title: "Rock Paper Scissors",
  },
  erc7984: {
    contract: "contracts/openzeppelin/ERC7984.sol",
    test: "test/openzeppelin/ERC7984.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0",
    },
    description: "Confidential token using OpenZeppelin's ERC7984 standard",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/erc7984.md",
    title: "ERC7984",
  },
  "erc7984-erc20-wrapper": {
    contract: "contracts/openzeppelin/ERC7984ERC20Wrapper.sol",
    test: "test/openzeppelin/ERC7984ERC20Wrapper.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0",
    },
    dependencies: ["contracts/openzeppelin/mocks/ERC20Mock.sol"],
    description: "Wraps ERC20 tokens into confidential ERC7984 tokens",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/erc7984-erc20-wrapper.md",
    title: "ERC7984 ERC20 Wrapper",
  },
  "swap-erc7984-to-erc20": {
    contract: "contracts/openzeppelin/SwapERC7984ToERC20.sol",
    test: "test/openzeppelin/SwapERC7984ToERC20.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0",
    },
    dependencies: [
      "contracts/openzeppelin/mocks/ERC20Mock.sol",
      "contracts/openzeppelin/ERC7984.sol",
    ],
    description: "Swap confidential ERC7984 tokens to regular ERC20 tokens",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/swap-erc7984-to-erc20.md",
    title: "Swap ERC7984 To ERC20",
  },
  "swap-erc7984-to-erc7984": {
    contract: "contracts/openzeppelin/SwapERC7984ToERC7984.sol",
    test: "test/openzeppelin/SwapERC7984ToERC7984.ts",
    npmDependencies: {
      "@openzeppelin/confidential-contracts": "^0.3.0",
    },
    dependencies: ["contracts/openzeppelin/ERC7984.sol"],
    description: "Fully confidential swap between two ERC7984 tokens",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/swap-erc7984-to-erc7984.md",
    title: "Swap ERC7984 To ERC7984",
  },
  "vesting-wallet": {
    contract: "contracts/openzeppelin/VestingWallet.sol",
    test: "test/openzeppelin/VestingWallet.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0",
    },
    dependencies: ["contracts/openzeppelin/ERC7984.sol"],
    description:
      "Linear vesting wallet for ERC7984 tokens - amounts stay encrypted!",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/vesting-wallet.md",
    title: "Vesting Wallet",
  },
};

// =============================================================================
// Category Configurations
// =============================================================================

export const CATEGORIES: Record<string, CategoryConfig> = {
  advanced: {
    name: "Advanced Examples",
    contracts: [
      {
        sol: "contracts/advanced/BlindAuction.sol",
        test: "test/advanced/BlindAuction.ts",
      },
      {
        sol: "contracts/advanced/EncryptedEscrow.sol",
        test: "test/advanced/EncryptedEscrow.ts",
      },
      {
        sol: "contracts/advanced/HiddenVoting.sol",
        test: "test/advanced/HiddenVoting.ts",
      },
      {
        sol: "contracts/advanced/PrivateKYC.sol",
        test: "test/advanced/PrivateKYC.ts",
      },
      {
        sol: "contracts/advanced/PrivatePayroll.sol",
        test: "test/advanced/PrivatePayroll.ts",
      },
    ],
  },
  basicdecryption: {
    name: "Basic - Decryption Examples",
    contracts: [
      {
        sol: "contracts/basic/decryption/PublicDecryptMultipleValues.sol",
        test: "test/basic/decryption/PublicDecryptMultipleValues.ts",
      },
      {
        sol: "contracts/basic/decryption/PublicDecryptSingleValue.sol",
        test: "test/basic/decryption/PublicDecryptSingleValue.ts",
      },
      {
        sol: "contracts/basic/decryption/UserDecryptMultipleValues.sol",
        test: "test/basic/decryption/UserDecryptMultipleValues.ts",
      },
      {
        sol: "contracts/basic/decryption/UserDecryptSingleValue.sol",
        test: "test/basic/decryption/UserDecryptSingleValue.ts",
      },
    ],
  },
  basicencryption: {
    name: "Basic - Encryption Examples",
    contracts: [
      {
        sol: "contracts/basic/encryption/EncryptMultipleValues.sol",
        test: "test/basic/encryption/EncryptMultipleValues.ts",
      },
      {
        sol: "contracts/basic/encryption/EncryptSingleValue.sol",
        test: "test/basic/encryption/EncryptSingleValue.ts",
      },
      {
        sol: "contracts/basic/encryption/FHECounter.sol",
        test: "test/basic/encryption/FHECounter.ts",
      },
    ],
  },
  basicfheoperations: {
    name: "Basic - FHE Operations Examples",
    contracts: [
      {
        sol: "contracts/basic/fhe-operations/FHEAdd.sol",
        test: "test/basic/fhe-operations/FHEAdd.ts",
      },
      {
        sol: "contracts/basic/fhe-operations/FHEArithmetic.sol",
        test: "test/basic/fhe-operations/FHEArithmetic.ts",
      },
      {
        sol: "contracts/basic/fhe-operations/FHEComparison.sol",
        test: "test/basic/fhe-operations/FHEComparison.ts",
      },
      {
        sol: "contracts/basic/fhe-operations/FHEIfThenElse.sol",
        test: "test/basic/fhe-operations/FHEIfThenElse.ts",
      },
    ],
  },
  concepts: {
    name: "Concepts Examples",
    contracts: [
      {
        sol: "contracts/concepts/FHEAccessControl.sol",
        test: "test/concepts/FHEAccessControl.ts",
      },
      {
        sol: "contracts/concepts/FHEAntiPatterns.sol",
        test: "test/concepts/FHEAntiPatterns.ts",
      },
      {
        sol: "contracts/concepts/FHEHandles.sol",
        test: "test/concepts/FHEHandles.ts",
      },
      {
        sol: "contracts/concepts/FHEInputProof.sol",
        test: "test/concepts/FHEInputProof.ts",
      },
    ],
  },
  gaming: {
    name: "Gaming Examples",
    contracts: [
      {
        sol: "contracts/gaming/EncryptedLottery.sol",
        test: "test/gaming/EncryptedLottery.ts",
      },
      {
        sol: "contracts/gaming/EncryptedPoker.sol",
        test: "test/gaming/EncryptedPoker.ts",
      },
      {
        sol: "contracts/gaming/RockPaperScissors.sol",
        test: "test/gaming/RockPaperScissors.ts",
      },
    ],
  },
  openzeppelin: {
    name: "Openzeppelin Examples",
    contracts: [
      {
        sol: "contracts/openzeppelin/ERC7984.sol",
        test: "test/openzeppelin/ERC7984.ts",
      },
      {
        sol: "contracts/openzeppelin/ERC7984ERC20Wrapper.sol",
        test: "test/openzeppelin/ERC7984ERC20Wrapper.ts",
      },
      {
        sol: "contracts/openzeppelin/SwapERC7984ToERC20.sol",
        test: "test/openzeppelin/SwapERC7984ToERC20.ts",
      },
      {
        sol: "contracts/openzeppelin/SwapERC7984ToERC7984.sol",
        test: "test/openzeppelin/SwapERC7984ToERC7984.ts",
      },
      {
        sol: "contracts/openzeppelin/VestingWallet.sol",
        test: "test/openzeppelin/VestingWallet.ts",
      },
    ],
  },
};

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Get list of example names
 */
export function getExampleNames(): string[] {
  return Object.keys(EXAMPLES);
}

/**
 * Get list of category names
 */
export function getCategoryNames(): string[] {
  return Object.keys(CATEGORIES);
}

/**
 * Get example by name
 */
export function getExample(name: string): ExampleConfig | undefined {
  return EXAMPLES[name];
}

/**
 * Get category by name
 */
export function getCategory(name: string): CategoryConfig | undefined {
  return CATEGORIES[name];
}

/**
 * Generate consistent docs filename with fhe- prefix
 */
export function getDocsFileName(exampleName: string): string {
  return exampleName.startsWith("fhe-") ? exampleName : `fhe-${exampleName}`;
}
