/**
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY ⚠️
 *
 * This file is auto-generated by cli/generate-config.ts
 * Run 'npm run generate:config' to regenerate
 */

// =============================================================================
// Types
// =============================================================================

export interface ExampleConfig {
  /** Path to the Solidity contract file */
  contract: string;
  /** Path to the TypeScript test file */
  test: string;
  /** Optional additional contract dependencies */
  dependencies?: string[];
  /** Optional npm packages to install */
  npmDependencies?: Record<string, string>;
  /** Full description for documentation */
  description: string;
  /** Category for grouping */
  category: string;
  /** Output path for generated documentation */
  docsOutput: string;
  /** Title for documentation */
  title: string;
}

export interface CategoryConfig {
  /** Display name */
  name: string;
  /** List of contracts in this category */
  contracts: Array<{ sol: string; test?: string }>;
}

// =============================================================================
// Example Configurations
// =============================================================================

export const EXAMPLES: Record<string, ExampleConfig> = {
  "blind-auction": {
    contract: "contracts/advanced/BlindAuction.sol",
    test: "test/advanced/BlindAuction.ts",
    description:
      "Blind auction where bids remain fully encrypted until the end. Uses FHE.gt/select to find the winner without decrypting losing bids. Only the winning amount is revealed after the auction closes.",
    category: "Advanced",
    docsOutput: "docs/advanced/blind-auction.md",
    title: "Blind Auction"
  },
  "encrypted-escrow": {
    contract: "contracts/advanced/EncryptedEscrow.sol",
    test: "test/advanced/EncryptedEscrow.ts",
    description:
      "Confidential escrow service with hidden transaction amounts and arbiters. Secures funds with encrypted amounts. Details remain hidden until release or refund, supporting multi-party dispute resolution.",
    category: "Advanced",
    docsOutput: "docs/advanced/encrypted-escrow.md",
    title: "Encrypted Escrow"
  },
  "hidden-voting": {
    contract: "contracts/advanced/HiddenVoting.sol",
    test: "test/advanced/HiddenVoting.ts",
    description:
      "Private voting system with homomorphic vote tallying (Yes/No). Ballots are added without decryption. Only final totals are revealed, ensuring individual vote secrecy forever.",
    category: "Advanced",
    docsOutput: "docs/advanced/hidden-voting.md",
    title: "Hidden Voting"
  },
  "private-kyc": {
    contract: "contracts/advanced/PrivateKYC.sol",
    test: "test/advanced/PrivateKYC.ts",
    description:
      "Privacy-preserving KYC using encrypted predicate proofs (e.g., 18+ check). Users submit encrypted data. The contract verifies compliance without learning actual values, returning encrypted booleans.",
    category: "Advanced",
    docsOutput: "docs/advanced/private-kyc.md",
    title: "Private KYC"
  },
  "private-payroll": {
    contract: "contracts/advanced/PrivatePayroll.sol",
    test: "test/advanced/PrivatePayroll.ts",
    description:
      "Confidential payroll system with encrypted salaries and selective access. Employers manage employees with hidden salaries. Only the owner and the respective employee can access specific salary data.",
    category: "Advanced",
    docsOutput: "docs/advanced/private-payroll.md",
    title: "Private Payroll"
  },
  "public-decrypt-multiple-values": {
    contract: "contracts/basic/decryption/PublicDecryptMultipleValues.sol",
    test: "test/basic/decryption/PublicDecryptMultipleValues.ts",
    description:
      "Dice game demonstrating public decryption of multiple encrypted values. Shows how to use checkSignatures() with multiple values, highlighting that the order in cts[] must match the ABI-encoded results.",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/public-decrypt-multiple-values.md",
    title: "Public Decrypt Multiple Values"
  },
  "public-decrypt-single-value": {
    contract: "contracts/basic/decryption/PublicDecryptSingleValue.sol",
    test: "test/basic/decryption/PublicDecryptSingleValue.ts",
    description:
      "Heads or Tails game with public, permissionless decryption. Demonstrates FHE.makePubliclyDecryptable(), allowing any user to decrypt results like game outcomes or voting tallies using KMS proofs.",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/public-decrypt-single-value.md",
    title: "Public Decrypt Single Value"
  },
  "user-decrypt-multiple-values": {
    contract: "contracts/basic/decryption/UserDecryptMultipleValues.sol",
    test: "test/basic/decryption/UserDecryptMultipleValues.ts",
    description:
      "Decrypting multiple encrypted values (ebool, euint32, euint64) for a user. Highlights that each value requires individual permission grants, as there is no batching for FHE.allow() or FHE.allowThis().",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/user-decrypt-multiple-values.md",
    title: "User Decrypt Multiple Values"
  },
  "user-decrypt-single-value": {
    contract: "contracts/basic/decryption/UserDecryptSingleValue.sol",
    test: "test/basic/decryption/UserDecryptSingleValue.ts",
    description:
      "User-controlled decryption with mandatory two-step permissions. Demonstrates the pattern: allowThis() for contract storage/computation and allow() for user decryption, illustrating correct vs incorrect usage.",
    category: "Basic - Decryption",
    docsOutput: "docs/basic/decryption/user-decrypt-single-value.md",
    title: "User Decrypt Single Value"
  },
  "encrypt-multiple-values": {
    contract: "contracts/basic/encryption/EncryptMultipleValues.sol",
    test: "test/basic/encryption/EncryptMultipleValues.ts",
    description:
      "Efficient handling of multiple encrypted values via batched inputs. Uses a single proof for multiple values (ebool, euint32, eaddress), saving significant gas compared to separate proofs.",
    category: "Basic - Encryption",
    docsOutput: "docs/basic/encryption/encrypt-multiple-values.md",
    title: "Encrypt Multiple Values"
  },
  "encrypt-single-value": {
    contract: "contracts/basic/encryption/EncryptSingleValue.sol",
    test: "test/basic/encryption/EncryptSingleValue.ts",
    description:
      "Single value encryption with proof validation. Shows how to receive encrypted data from users, validate proofs, and grant proper permissions. Includes examples of common mistakes and the correct permission pattern (allowThis + allow).",
    category: "Basic - Encryption",
    docsOutput: "docs/basic/encryption/encrypt-single-value.md",
    title: "Encrypt Single Value"
  },
  "fhe-counter": {
    contract: "contracts/basic/encryption/FHECounter.sol",
    test: "test/basic/encryption/FHECounter.ts",
    description:
      "Confidential counter with encrypted increment/decrement operations. Demonstrates the FHE workflow: encryption, computation, and permission management while keeping the counter value private.",
    category: "Basic - Encryption",
    docsOutput: "docs/basic/encryption/fhe-counter.md",
    title: "FHE Counter"
  },
  "fhe-add": {
    contract: "contracts/basic/fhe-operations/FHEAdd.sol",
    test: "test/basic/fhe-operations/FHEAdd.ts",
    description:
      "Introduction to homomorphic addition on encrypted values. Demonstrates adding two encrypted numbers without decryption, including input handling, addition, and permission management.",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-add.md",
    title: "FHE Add"
  },
  "fhe-arithmetic": {
    contract: "contracts/basic/fhe-operations/FHEArithmetic.sol",
    test: "test/basic/fhe-operations/FHEArithmetic.ts",
    description:
      "FHE arithmetic (add, sub, mul, div, rem, min, max) on encrypted values. Includes gas cost comparisons and key limitations, such as plaintext divisors for division and remainder operations.",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-arithmetic.md",
    title: "FHE Arithmetic"
  },
  "fhe-comparison": {
    contract: "contracts/basic/fhe-operations/FHEComparison.sol",
    test: "test/basic/fhe-operations/FHEComparison.ts",
    description:
      "Encrypted comparisons (eq, ne, gt, lt, ge, le) and conditional selection. Demonstrates FHE.select for branching without information leakage, essential for \"find maximum\" or threshold logic.",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-comparison.md",
    title: "FHE Comparison"
  },
  "fhe-if-then-else": {
    contract: "contracts/basic/fhe-operations/FHEIfThenElse.sol",
    test: "test/basic/fhe-operations/FHEIfThenElse.ts",
    description:
      "Conditional logic using FHE.select for privacy-preserving branching. Demonstrates if-then-else logic on encrypted values. Unlike regular if/else, FHE.select avoids information leakage by evaluating both branches.",
    category: "Basic - FHE Operations",
    docsOutput: "docs/basic/fhe-operations/fhe-if-then-else.md",
    title: "FHE If Then Else"
  },
  "control-flow": {
    contract: "contracts/concepts/antipatterns/ControlFlow.sol",
    test: "test/concepts/antipatterns/ControlFlow.ts",
    description:
      "Control flow anti-patterns in FHE development. Demonstrates mistakes with conditional logic and loops on encrypted values, providing correct vs incorrect implementations.",
    category: "Concepts - Antipatterns",
    docsOutput: "docs/concepts/antipatterns/control-flow.md",
    title: "Control Flow"
  },
  "operations-gas-noise": {
    contract: "contracts/concepts/antipatterns/OperationsGasNoise.sol",
    test: "test/concepts/antipatterns/OperationsGasNoise.ts",
    description:
      "Operations, gas, and noise anti-patterns in FHE development. Covers performance issues, side-channel leaks, noise accumulation, and inefficient encrypted computation patterns.",
    category: "Concepts - Antipatterns",
    docsOutput: "docs/concepts/antipatterns/operations-gas-noise.md",
    title: "Operations Gas Noise"
  },
  "permissions": {
    contract: "contracts/concepts/antipatterns/Permissions.sol",
    test: "test/concepts/antipatterns/Permissions.ts",
    description:
      "Permission management anti-patterns in FHE development. Covers mistakes with allowThis, allow, and permission propagation across transfers and cross-contract calls.",
    category: "Concepts - Antipatterns",
    docsOutput: "docs/concepts/antipatterns/permissions.md",
    title: "Permissions"
  },
  "fhe-access-control": {
    contract: "contracts/concepts/core/FHEAccessControl.sol",
    test: "test/concepts/core/FHEAccessControl.ts",
    description:
      "FHE permission patterns: allow() permanent, allowThis() contract, and allowTransient() temporary access. Demonstrates usage to prevent common decryption failures.",
    category: "Concepts - Core",
    docsOutput: "docs/concepts/core/fhe-access-control.md",
    title: "FHE Access Control"
  },
  "fhe-handles": {
    contract: "contracts/concepts/core/FHEHandles.sol",
    test: "test/concepts/core/FHEHandles.ts",
    description:
      "Deep dive into FHE handles: uint256 pointers to encrypted data. Demonstrates handle creation (fromExternal, asEuint, operations) and emphasizes their immutability—each operation creates a NEW handle.",
    category: "Concepts - Core",
    docsOutput: "docs/concepts/core/fhe-handles.md",
    title: "FHE Handles"
  },
  "fhe-input-proof": {
    contract: "contracts/concepts/core/FHEInputProof.sol",
    test: "test/concepts/core/FHEInputProof.ts",
    description:
      "Input proof validation and batching strategies in FHEVM. Explains why proofs are essential (preventing replay attacks and invalid data) and demonstrates gas-efficient batching where one proof validates multiple encrypted inputs.",
    category: "Concepts - Core",
    docsOutput: "docs/concepts/core/fhe-input-proof.md",
    title: "FHE Input Proof"
  },
  "encrypted-lottery": {
    contract: "contracts/gaming/EncryptedLottery.sol",
    test: "test/gaming/EncryptedLottery.ts",
    description:
      "Provably fair lottery with encrypted ticket numbers and FHE randomness. Players buy tickets with hidden numbers. Winners are determined by comparing encrypted values, ensuring no one sees numbers before the draw.",
    category: "Gaming",
    docsOutput: "docs/gaming/encrypted-lottery.md",
    title: "Encrypted Lottery"
  },
  "encrypted-poker": {
    contract: "contracts/gaming/EncryptedPoker.sol",
    test: "test/gaming/EncryptedPoker.ts",
    description:
      "On-chain Texas Hold'em poker with encrypted hole cards and hand strengths. Hole cards remain hidden throughout. Winners are determined by comparing encrypted hand strengths, demonstrating complex multi-state game logic.",
    category: "Gaming",
    docsOutput: "docs/gaming/encrypted-poker.md",
    title: "Encrypted Poker"
  },
  "rock-paper-scissors": {
    contract: "contracts/gaming/RockPaperScissors.sol",
    test: "test/gaming/RockPaperScissors.ts",
    description:
      "Fair Rock-Paper-Scissors game with encrypted moves. Neither player can see the other's choice before committing. Winners are determined via FHE and revealed publicly, ensuring decentralized fairness.",
    category: "Gaming",
    docsOutput: "docs/gaming/rock-paper-scissors.md",
    title: "Rock Paper Scissors"
  },
  "erc7984": {
    contract: "contracts/openzeppelin/ERC7984.sol",
    test: "test/openzeppelin/ERC7984.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0"
    },
    description:
      "Confidential ERC20-compatible token using the ERC7984 standard. Supports encrypted balances and transfers with optional private minting, serving as a foundation for privacy-focused DeFi applications.",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/erc7984.md",
    title: "ERC7984"
  },
  "erc7984-erc20-wrapper": {
    contract: "contracts/openzeppelin/ERC7984ERC20Wrapper.sol",
    test: "test/openzeppelin/ERC7984ERC20Wrapper.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0"
    },
    dependencies: [
      "contracts/openzeppelin/mocks/ERC20Mock.sol"
    ],
    description:
      "Bridge between public ERC20 and confidential ERC7984 tokens. Enables wrapping (public → private) and unwrapping (private → public) of tokens, facilitating migration into the confidential ecosystem.",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/erc7984-erc20-wrapper.md",
    title: "ERC7984 ERC20 Wrapper"
  },
  "swap-erc7984-to-erc20": {
    contract: "contracts/openzeppelin/SwapERC7984ToERC20.sol",
    test: "test/openzeppelin/SwapERC7984ToERC20.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0"
    },
    dependencies: [
      "contracts/openzeppelin/mocks/ERC20Mock.sol",
      "contracts/openzeppelin/ERC7984.sol"
    ],
    description:
      "Atomic swap from confidential ERC7984 to public ERC20 tokens. Demonstrates a two-step swap process using FHEVM v0.9 public decryption flow (makePubliclyDecryptable and checkSignatures) for trustless swaps.",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/swap-erc7984-to-erc20.md",
    title: "Swap ERC7984 To ERC20"
  },
  "swap-erc7984-to-erc7984": {
    contract: "contracts/openzeppelin/SwapERC7984ToERC7984.sol",
    test: "test/openzeppelin/SwapERC7984ToERC7984.ts",
    npmDependencies: {
      "@openzeppelin/confidential-contracts": "^0.3.0"
    },
    dependencies: [
      "contracts/openzeppelin/ERC7984.sol"
    ],
    description:
      "Fully private atomic swap between two confidential ERC7984 tokens. Both input and output amounts remain encrypted throughout—no decryption is needed, ensuring complete privacy from start to finish.",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/swap-erc7984-to-erc7984.md",
    title: "Swap ERC7984 To ERC7984"
  },
  "vesting-wallet": {
    contract: "contracts/openzeppelin/VestingWallet.sol",
    test: "test/openzeppelin/VestingWallet.ts",
    npmDependencies: {
      "@openzeppelin/contracts": "^5.4.0",
      "@openzeppelin/confidential-contracts": "^0.3.0"
    },
    dependencies: [
      "contracts/openzeppelin/ERC7984.sol"
    ],
    description:
      "Time-locked vesting wallet with fully encrypted token amounts. Implements linear vesting for ERC7984 tokens where the schedule, amounts, and releases are computed via FHE, keeping progress hidden from observers.",
    category: "Openzeppelin",
    docsOutput: "docs/openzeppelin/vesting-wallet.md",
    title: "Vesting Wallet"
  }
};

// =============================================================================
// Category Configurations
// =============================================================================

export const CATEGORIES: Record<string, CategoryConfig> = {
  basicencryption: {
    name: "Basic - Encryption",
    contracts: [
      {
        sol: "contracts/basic/encryption/EncryptMultipleValues.sol",
        test: "test/basic/encryption/EncryptMultipleValues.ts",
      },
      {
        sol: "contracts/basic/encryption/EncryptSingleValue.sol",
        test: "test/basic/encryption/EncryptSingleValue.ts",
      },
      {
        sol: "contracts/basic/encryption/FHECounter.sol",
        test: "test/basic/encryption/FHECounter.ts",
      }
    ],
  },
  basicdecryption: {
    name: "Basic - Decryption",
    contracts: [
      {
        sol: "contracts/basic/decryption/PublicDecryptMultipleValues.sol",
        test: "test/basic/decryption/PublicDecryptMultipleValues.ts",
      },
      {
        sol: "contracts/basic/decryption/PublicDecryptSingleValue.sol",
        test: "test/basic/decryption/PublicDecryptSingleValue.ts",
      },
      {
        sol: "contracts/basic/decryption/UserDecryptMultipleValues.sol",
        test: "test/basic/decryption/UserDecryptMultipleValues.ts",
      },
      {
        sol: "contracts/basic/decryption/UserDecryptSingleValue.sol",
        test: "test/basic/decryption/UserDecryptSingleValue.ts",
      }
    ],
  },
  basicfheoperations: {
    name: "Basic - FHE Operations",
    contracts: [
      {
        sol: "contracts/basic/fhe-operations/FHEAdd.sol",
        test: "test/basic/fhe-operations/FHEAdd.ts",
      },
      {
        sol: "contracts/basic/fhe-operations/FHEArithmetic.sol",
        test: "test/basic/fhe-operations/FHEArithmetic.ts",
      },
      {
        sol: "contracts/basic/fhe-operations/FHEComparison.sol",
        test: "test/basic/fhe-operations/FHEComparison.ts",
      },
      {
        sol: "contracts/basic/fhe-operations/FHEIfThenElse.sol",
        test: "test/basic/fhe-operations/FHEIfThenElse.ts",
      }
    ],
  },
  conceptscore: {
    name: "Concepts - Core",
    contracts: [
      {
        sol: "contracts/concepts/core/FHEAccessControl.sol",
        test: "test/concepts/core/FHEAccessControl.ts",
      },
      {
        sol: "contracts/concepts/core/FHEHandles.sol",
        test: "test/concepts/core/FHEHandles.ts",
      },
      {
        sol: "contracts/concepts/core/FHEInputProof.sol",
        test: "test/concepts/core/FHEInputProof.ts",
      }
    ],
  },
  conceptsantipatterns: {
    name: "Concepts - Antipatterns",
    contracts: [
      {
        sol: "contracts/concepts/antipatterns/ControlFlow.sol",
        test: "test/concepts/antipatterns/ControlFlow.ts",
      },
      {
        sol: "contracts/concepts/antipatterns/OperationsGasNoise.sol",
        test: "test/concepts/antipatterns/OperationsGasNoise.ts",
      },
      {
        sol: "contracts/concepts/antipatterns/Permissions.sol",
        test: "test/concepts/antipatterns/Permissions.ts",
      }
    ],
  },
  gaming: {
    name: "Gaming",
    contracts: [
      {
        sol: "contracts/gaming/EncryptedLottery.sol",
        test: "test/gaming/EncryptedLottery.ts",
      },
      {
        sol: "contracts/gaming/EncryptedPoker.sol",
        test: "test/gaming/EncryptedPoker.ts",
      },
      {
        sol: "contracts/gaming/RockPaperScissors.sol",
        test: "test/gaming/RockPaperScissors.ts",
      }
    ],
  },
  advanced: {
    name: "Advanced",
    contracts: [
      {
        sol: "contracts/advanced/BlindAuction.sol",
        test: "test/advanced/BlindAuction.ts",
      },
      {
        sol: "contracts/advanced/EncryptedEscrow.sol",
        test: "test/advanced/EncryptedEscrow.ts",
      },
      {
        sol: "contracts/advanced/HiddenVoting.sol",
        test: "test/advanced/HiddenVoting.ts",
      },
      {
        sol: "contracts/advanced/PrivateKYC.sol",
        test: "test/advanced/PrivateKYC.ts",
      },
      {
        sol: "contracts/advanced/PrivatePayroll.sol",
        test: "test/advanced/PrivatePayroll.ts",
      }
    ],
  },
  openzeppelin: {
    name: "Openzeppelin",
    contracts: [
      {
        sol: "contracts/openzeppelin/ERC7984.sol",
        test: "test/openzeppelin/ERC7984.ts",
      },
      {
        sol: "contracts/openzeppelin/ERC7984ERC20Wrapper.sol",
        test: "test/openzeppelin/ERC7984ERC20Wrapper.ts",
      },
      {
        sol: "contracts/openzeppelin/SwapERC7984ToERC20.sol",
        test: "test/openzeppelin/SwapERC7984ToERC20.ts",
      },
      {
        sol: "contracts/openzeppelin/SwapERC7984ToERC7984.sol",
        test: "test/openzeppelin/SwapERC7984ToERC7984.ts",
      },
      {
        sol: "contracts/openzeppelin/VestingWallet.sol",
        test: "test/openzeppelin/VestingWallet.ts",
      }
    ],
  }
};

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Get list of example names
 */
export function getExampleNames(): string[] {
  return Object.keys(EXAMPLES);
}

/**
 * Get list of category names
 */
export function getCategoryNames(): string[] {
  return Object.keys(CATEGORIES);
}

/**
 * Get example by name
 */
export function getExample(name: string): ExampleConfig | undefined {
  return EXAMPLES[name];
}

/**
 * Get category by name
 */
export function getCategory(name: string): CategoryConfig | undefined {
  return CATEGORIES[name];
}

/**
 * Generate consistent docs filename with fhe- prefix
 */
export function getDocsFileName(exampleName: string): string {
  return exampleName.startsWith("fhe-") ? exampleName : `fhe-${exampleName}`;
}
